apiVersion: batch/v1
kind: Job
metadata:
  name: firstdb
spec:
  template:
    spec:
      containers:
      - name: firstdb
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h","xm-postgres", "-U", "xm", "auth_svc" ]
        env:
        - name: PGPASSWORD
          value: password
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: secondb
spec:
  template:
    spec:
      containers:
      - name: secondb
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h","xm-postgres", "-U", "xm", "company_svc" ]
        env:
        - name: PGPASSWORD
          value: password
      restartPolicy: Never