apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: xm-postgres                          # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: xm-postgres
spec:
  clusterIP: 10.96.247.215
  clusterIPs:
  - 10.96.247.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:                                         # Selects any Pod with labels `app=xm-postgres,tier=postgres`
    app: xm-postgres
    tier: postgres