apiVersion: v1
kind: Service
metadata:
  labels:
    app: xm-gateway
  name: xm-gateway-srv
spec:
  clusterIP: 10.101.216.171
  clusterIPs:
  - 10.101.216.171
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32717
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: xm-gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost